### ISSUE TITLE
Fix code runner to accept a one-line code block

### ISSUE THREAD

**Issue by Jus-Codin** [czlucius/ampere#14]
Code runner in [coderunner.py](https://github.com/czlucius/ampere/blob/main/components/run/coderunner.py) currently only checks for backticks in the code and removes the whole first line.

This works for code blocks in this format:
```
```<lang>
<code>```
```
But it does not work for code blocks in one line:
```
```<code>```
```

This should be able to be easily fixed, I'll probably submit a pull request

**Comment by czlucius** [comment]
Note for fix:
After fix, \`\`\`\`\`\` will cause a crash

**Comment by Jus-Codin** [comment]
> Note for fix: After fix, `````` will cause a crash

It appears that even before the fix, an empty codeblock would also result in a crash since both codes should produce the same output with an empty codeblock?

**Comment by Jus-Codin** [comment]
@czlucius After looking at the old code, it this issue seems unrelated, but a basic check if `content` is empty should be enough

**Comment by czlucius** [comment]
Ok

**Comment by czlucius** [comment]
> > Note for fix: After fix, `````` will cause a crash
> 
> It appears that even before the fix, an empty codeblock would also result in a crash since both codes should produce the same output with an empty codeblock?

Yes, both produce an empty string after stripping, but [1:] returns an empty list while [0] has index error

**Comment by czlucius** [comment]
I will go fix this
