### ISSUE TITLE
Use aiohttp instead of urllib.request

### ISSUE THREAD

**Issue by Jus-Codin** [czlucius/ampere#15]
The code in [libdl.py](https://github.com/czlucius/ampere/blob/main/components/run/libdl.py) currently uses urllib.request to send http requests. This shouldn't be used as it is blocking, so an asyncronous library should be used. I would suggest using [aiohttp](https://github.com/aio-libs/aiohttp), since pycord already uses it so it won't add any extra dependencies.

**Comment by czlucius** [comment]
Ok, I'll look into this.
Thanks

**Comment by czlucius** [comment]
Hi @Jus-Codin 
I've changed to `aiohttp` like you said, and for new features, I have continued use of that library.
Thanks for the suggestion!
